### ISSUE TITLE
On website, add option to make walkways near-equal height to surrounding ground

### ISSUE THREAD

**Issue by jaredcoh** [skarkkai/touch-mapper#21]
I understand from the perspective of a visible disabled person, having the walkways be clearly defined is helpful. 
I do think that there is benefit in having the website provide an option to make the walkways not "go underground". I believe there is a simple in the code, where a parameter is turned from true to false, but it is not available on the website as an option to have.

**Comment by skarkkai** [comment]
What do you mean by walkways going underground? What is the problem you are having with the way walkways are handled currently?

**Comment by jaredcoh** [comment]
The picture below may show it here: 
![image](https://user-images.githubusercontent.com/76497624/233849111-ba3b6bf4-3b48-42f8-93d4-9390b08ce6ca.png)
This is a picture of Carnegie Mellon University, and the large X in the middle is a walkway that crosses between several buildings. On the stl that is automatically generated on the website, it appears that this is significantly lowered compared to the ground surrounding it. I was curious if there was a way to remove the significant height difference between the walkway and the ground.

Let me know if this makes sense! Thank you :)

**Comment by skarkkai** [comment]
This is very likely because the entire grass field has been defined as a recreational area, which is treated by Touch Mapper the same as pedestrian footways, so they are raised. The paths might be treated as something too small to include on the map, so their area is treated like other areas that contain "nothing". So they end up lower than the grass field.

Screenshot from openstreetmap.org editor.

![image](https://user-images.githubusercontent.com/1282262/233849808-89221c08-312e-432c-8540-f0ce81bbf2a1.png)

**Comment by jaredcoh** [comment]
Thank you sthat makes total sense. I appreciate the explanation!
